# Generated by Django 2.2.6 on 2019-11-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='pincode',
            new_name='Pincode',
        ),
    ]
