# Generated by Django 2.2.6 on 2019-11-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('customer_address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('phone', models.BigIntegerField()),
            ],
        ),
    ]
