# Generated by Django 2.2.6 on 2019-11-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='detail',
            new_name='details',
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.IntegerField(blank=True, default=50),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(blank=True, default='abc', max_length=100),
        ),
    ]
