# Generated by Django 2.2.6 on 2019-11-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191109_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank='True', upload_to=''),
        ),
    ]
